services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employees_management_system
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
